### PR TITLE
Don't track monero binaries and data

### PR DESCRIPTION
**Pull request by trasherdk**

### CODE REVIEW

**Comment by woodser** [comment]
The folders being added to ignore are not currently used by the project.

**Comment by trasherdk** [comment]
Correct. They hold the monero binaries and blockchain.
I will later add a script to start/stop daemon and wallet easily, when I'm satisfied with it.

**Comment by trasherdk** [comment]
Okay. I moved those directories to a gitignore_global
Do you want the scripts, once they are ready?

**Comment by woodser** [comment]
Sure scripts to start and stop the daemon easily would be nice.

**Pull request closed without merging**
